### ISSUE TITLE
Casting problem

### ISSUE THREAD

**Issue by pettydraper** [pranav-prakash/RokuCast#50] opened 2019-09-21 18:26 UTC
Hi @pranav-prakash, thanks for the great extension. It's stellar. Lately, however, I've been having trouble using due to (I think?) a recent Roku firmware update. No problem detecting videos, but will not cast. When attempting to cast a video, the splash page will briefly load, but it fails thereafter and goes back to the home screen. If you have the time, could you take a look into it?

My Chrome is running version 76.0.3809.132 (Official Build) (64-bit) and my Roku is on 9.1.0 (build 4919-24). Thank you!

**Comment by pranav-prakash** [comment] 2019-09-21 18:29
I don't have a Roku with me so it might be hard to debug. Can you try posting the console output from the extension (can be found in "inspect views: background.html" in the extensions page).

**Comment by pettydraper** [comment] 2019-09-21 19:04
I appreciate any help! Thanks. I did notice a [previous issue](https://github.com/pranav-prakash/RokuCast/issues/43) that had the same IP address as my Roku (192.168.1.12) with a similar problem, but I know that I have used the extension with my device successfully before.

```
background.js:28 [{…}]
0: 
active: true
audible: false
autoDiscardable: true
discarded: false
favIconUrl: "http://camendesign.com/favicon.ico"
height: 717
highlighted: true
id: 1359
incognito: false
index: 11
mutedInfo: {muted: false}
pinned: false
selected: true
status: "complete"
title: "“Video For Everybody” Test Page"
url: "http://camendesign.com/code/video_for_everybody/test.html"
width: 1349
windowId: 1
__proto__: Object
length: 1
__proto__: Array(0)
background.js:29 “Video For Everybody” Test Page
background.js:30 http://camendesign.com/favicon.ico
```

**Comment by pranav-prakash** [comment] 2019-09-21 19:16
I do not believe the ip address assigned to your Roku makes any difference.

I'm just guessing here but I think you're probably right in that it might have been caused by a recent roku update, because the video url is successfully sent from the extension but Roku seems to reject it. It's possible they might have changed the `play on roku` endpoint format.

One fix would be to use the version in the [master](https://github.com/pranav-prakash/RokuCast/tree/master) branch which has you sideload a separate receiver app to the Roku. The readme there should walk you through the steps, but let me know if the instructions are unclear.

**Comment by pettydraper** [comment] 2019-09-21 19:22
I'll try out the version in the master branch and see how it goes. Thanks for your checking out the issue. Appreciate it!

**Closed as completed** 2019-10-07 00:24 UTC

**Comment by dgreuel** [comment] 2019-11-10 05:44
@pranav-prakash @pettydraper It looks like the `Play on Roku` endpoint no longer likes being passed the `k=(null)` parameter. I updated [RokuKast](https://github.com/dgreuel/RokuKast/commit/b5672ab32fbd677198ba9149478a3817e90b4184) and it seems to work for me now.

**Comment by pranav-prakash** [comment] 2019-11-10 05:58
@dgreuel Nice find! I've updated it accordingly.
